name: Build Release APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'

      - name: Unzip Project
        run: unzip final-apk-ready-project.zip

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
